import type {
  SurveyCommunity,
  SurveyCommunityCard,
  SurveyCommunityFeatures,
  SurveyCommunityMe,
  SurveyDataMarket,
  SurveyDataMarketDetails,
  SurveyFeatures,
  SurveyStatus,
  SurveyTaking,
  SurveyTopic,
} from "../types";

// export const homeSurveysData = {
//   suitYouBest: [
//     {
//       Id: 1,
//       RequesterId: 1,
//       Title: "Khảo sát về xu hướng mua sắm Online",
//       Description:
//         "Đây là Khảo sát nhằm mục đích tìm hiểu xu hướng mua sắm online của người dùng, sau khi nền kinh tế đã phục hồi hậu COVID-19.",
//       SurveyTypeId: 2,
//       SurveyTopicId: 1,
//       SurveySpecificTopicId: 1,
//       StartDate: "2025-06-01",
//       EndDate: null,
//       Kpi: 1000,
//       SecurityModeId: 2,
//       TheoryPrice: 1000000,
//       ExtraPrice: 500000,
//       TakerBaseRewardPrice: 840, // AllocBaseAmount : Kpi
//       ProfitPrice: 300000, // (TheoryPrice + ExtraPrice) x 20%
//       AllocBaseAmount: 840000, // [(TheoryPrice + ExtraPrice) - ProfiPrice] x 70%
//       AllocTimeAmount: 240000, // [(TheoryPrice + ExtraPrice) - ProfiPrice] x 20%
//       AllocLevelAmount: 120000, // [(TheoryPrice + ExtraPrice) - ProfiPrice] x 10%
//       MaxXp: 100,
//       IsAvailable: true,
//       SlotsLeft: 10,
//       ConfigJsonString: "", // CHẮC CHẮN LÀ NULL
//       PublishedAt: null,
//       DeletedAt: null,
//       CreatedAt: null,
//       UpdatedAt: null,
//       SurveyStatusId: 2, // CHẮC CHẮN PHẢI LÀ 2
//       MainImageUrl:
//         "https://i.pinimg.com/736x/a7/4f/4f/a74f4fbb222bbb7365c9d0c5a86f701e.jpg",
//       BackgroundImageUrl:
//         "https://i.pinimg.com/736x/2a/f2/29/2af229ee740aa35340d90d19e35bc235.jpg",
//       CurrentSurveyRewardTracking: {
//         Id: 1,
//         SurveyId: 1, // TRÙNG VỚI ID Ở TRÊN
//         RewardPrice: 1200, // KHÔNG CAO HƠN (AllocBaseAmount + AllocTimeAmount) / 1000
//         RewardXp: 50, // KHÔNG CAO HƠN MaxXp
//         CreatedAt: "2025-06-17T05:15:51.251Z",
//       },
//     },
//     // GEN TIẾP 4 CÁI NỮA
//   ],
//   bigBonus: [
//     // GEN TIẾP 5 CÁI NỮA
//   ],
//   baseOnFavTopic: [
//    // GEN TIẾP 5 CÁI NỮA
//   ],
// };

export const homeSurveysData: SurveyCommunityFeatures = {
  suitYouBest: [],
  bigBonus: [],
  baseOnFavTopic: [],
};

export const homeSurveysAlternativeData: SurveyFeatures = {
  suitYouBest: [
    {
      Id: 1,
      RequesterId: 1,
      Title: "Khảo sát về thói quen tập luyện",
      Description:
        "Sức khỏe là thứ quan trọng nhất đối với bản thân mỗi người, việc giữ gìn sức khỏe và chăm chút nó bằng tập luyện là rất quan trọng. Với mục đích cải thiện thói quen tập luyện của mọi người tại Việt Nam, chúng tôi cần nắm bắt được bức tranh toàn cảnh. Hãy cho chúng tớ biết ngay nhé!",
      SurveyTypeId: 2,
      SurveyTopicId: 1,
      SurveySpecificTopicId: 1,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 1000,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/ad/24/7d/ad247d141dde8d782fff486b1196c981.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/2a/f2/29/2af229ee740aa35340d90d19e35bc235.jpg",
      CurrentSurveyRewardTracking: {
        Id: 1,
        SurveyId: 1,
        RewardPrice: 1200,
        RewardXp: 100,
        CreatedAt: "2025-06-17T05:19:54.611620Z",
      },
    },
    {
      Id: 2,
      RequesterId: 1,
      Title: "Khảo sát hành vi tiêu dùng Gen Z",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 1,
      SurveySpecificTopicId: 1,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/0f/67/5d/0f675d39d7462776702a0b9c6b3ec2c1.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/4e/6e/00/4e6e00d88cb8f7f994d29bb90b57b835.jpg",
      CurrentSurveyRewardTracking: {
        Id: 2,
        SurveyId: 2,
        RewardPrice: 1015,
        RewardXp: 96,
        CreatedAt: "2025-06-17T05:19:54.611218Z",
      },
    },
    {
      Id: 3,
      RequesterId: 1,
      Title: "Nghiên cứu thói quen ăn uống tại nhà",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 2,
      SurveySpecificTopicId: 2,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 10,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/91/12/cb/9112cbfb9bff030a4074dc60e86fe483.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/31/85/96/31859600f68c77370c3429cc6baf91e6.jpg",
      CurrentSurveyRewardTracking: {
        Id: 3,
        SurveyId: 3,
        RewardPrice: 945,
        RewardXp: 56,
        CreatedAt: "2025-06-17T05:19:54.611242Z",
      },
    },
    {
      Id: 4,
      RequesterId: 1,
      Title: "Khảo sát về ứng dụng công nghệ trong học tập",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 3,
      SurveySpecificTopicId: 3,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/ff/d2/d0/ffd2d063ffed34950f43897583e6c0a1.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/f9/63/22/f96322b6cf1aa352e6a963eb9a3f5373.jpg",
      CurrentSurveyRewardTracking: {
        Id: 4,
        SurveyId: 4,
        RewardPrice: 1028,
        RewardXp: 25,
        CreatedAt: "2025-06-17T05:19:54.611251Z",
      },
    },
    {
      Id: 5,
      RequesterId: 1,
      Title: "Đánh giá xu hướng đầu tư tài chính",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 4,
      SurveySpecificTopicId: 1,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/8f/6b/61/8f6b61e90a27aa8fbbfa856e47ccf3a7.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/4e/6e/00/4e6e00d88cb8f7f994d29bb90b57b835.jpg",
      CurrentSurveyRewardTracking: {
        Id: 5,
        SurveyId: 5,
        RewardPrice: 826,
        RewardXp: 71,
        CreatedAt: "2025-06-17T05:19:54.611263Z",
      },
    },
  ],
  bigBonus: [
    {
      Id: 6,
      RequesterId: 1,
      Title: "Thăm dò ý kiến về du lịch nội địa",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 1,
      SurveySpecificTopicId: 1,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 7,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/6f/36/4a/6f364acc107a90a1f744374a0052b939.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/4e/6e/00/4e6e00d88cb8f7f994d29bb90b57b835.jpg",
      CurrentSurveyRewardTracking: {
        Id: 6,
        SurveyId: 6,
        RewardPrice: 803,
        RewardXp: 69,
        CreatedAt: "2025-06-17T05:19:54.611369Z",
      },
    },
    {
      Id: 7,
      RequesterId: 1,
      Title: "Khảo sát nhu cầu mua sắm điện tử",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 2,
      SurveySpecificTopicId: 2,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 10,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/00/60/1e/00601e565109f3dea52df69e513372d8.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/31/85/96/31859600f68c77370c3429cc6baf91e6.jpg",
      CurrentSurveyRewardTracking: {
        Id: 7,
        SurveyId: 7,
        RewardPrice: 1022,
        RewardXp: 24,
        CreatedAt: "2025-06-17T05:19:54.611378Z",
      },
    },
    {
      Id: 8,
      RequesterId: 1,
      Title: "Nghiên cứu thói quen sử dụng mạng xã hội",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 3,
      SurveySpecificTopicId: 3,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 2,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/54/d0/8f/54d08fc96070505e4900e78057e29a88.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/f9/63/22/f96322b6cf1aa352e6a963eb9a3f5373.jpg",
      CurrentSurveyRewardTracking: {
        Id: 8,
        SurveyId: 8,
        RewardPrice: 921,
        RewardXp: 96,
        CreatedAt: "2025-06-17T05:19:54.611389Z",
      },
    },
    {
      Id: 9,
      RequesterId: 1,
      Title: "Khảo sát sở thích đọc sách hiện đại",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 4,
      SurveySpecificTopicId: 1,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 8,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/f9/8a/6d/f98a6d8ea4a45788b05aeb9be1603a5e.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/4e/6e/00/4e6e00d88cb8f7f994d29bb90b57b835.jpg",
      CurrentSurveyRewardTracking: {
        Id: 9,
        SurveyId: 9,
        RewardPrice: 827,
        RewardXp: 53,
        CreatedAt: "2025-06-17T05:19:54.611405Z",
      },
    },
    {
      Id: 10,
      RequesterId: 1,
      Title: "Thăm dò ý kiến về dịch vụ giao hàng",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 1,
      SurveySpecificTopicId: 2,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 5,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/04/f6/f5/04f6f59bd3612fa5f70d76191a4ae033.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/31/85/96/31859600f68c77370c3429cc6baf91e6.jpg",
      CurrentSurveyRewardTracking: {
        Id: 10,
        SurveyId: 10,
        RewardPrice: 811,
        RewardXp: 98,
        CreatedAt: "2025-06-17T05:19:54.611417Z",
      },
    },
  ],
  baseOnFavTopic: [
    {
      Id: 11,
      RequesterId: 1,
      Title: "Khảo sát chi tiêu cho giáo dục",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 1,
      SurveySpecificTopicId: 1,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/1c/98/3b/1c983b95a0388049f56f5f7c11c4daac.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/4e/6e/00/4e6e00d88cb8f7f994d29bb90b57b835.jpg",
      CurrentSurveyRewardTracking: {
        Id: 11,
        SurveyId: 11,
        RewardPrice: 808,
        RewardXp: 85,
        CreatedAt: "2025-06-17T05:19:54.611529Z",
      },
    },
    {
      Id: 12,
      RequesterId: 1,
      Title: "Khảo sát hành vi xem video online",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 2,
      SurveySpecificTopicId: 2,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/bb/1e/74/bb1e7425933edc5f1eaa7235052b8a48.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/31/85/96/31859600f68c77370c3429cc6baf91e6.jpg",
      CurrentSurveyRewardTracking: {
        Id: 12,
        SurveyId: 12,
        RewardPrice: 854,
        RewardXp: 40,
        CreatedAt: "2025-06-17T05:19:54.611538Z",
      },
    },
    {
      Id: 13,
      RequesterId: 1,
      Title: "Khảo sát trải nghiệm mua sắm tại siêu thị",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 3,
      SurveySpecificTopicId: 3,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/24/a7/ab/24a7ab9eceafe799e7da83f538356d0a.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/f9/63/22/f96322b6cf1aa352e6a963eb9a3f5373.jpg",
      CurrentSurveyRewardTracking: {
        Id: 13,
        SurveyId: 13,
        RewardPrice: 951,
        RewardXp: 27,
        CreatedAt: "2025-06-17T05:19:54.611546Z",
      },
    },
    {
      Id: 14,
      RequesterId: 1,
      Title: "Khảo sát sự quan tâm đến sức khỏe tinh thần",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 4,
      SurveySpecificTopicId: 1,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/78/bb/a7/78bba7eb4bae37fc4b6df099607bb2df.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/4e/6e/00/4e6e00d88cb8f7f994d29bb90b57b835.jpg",
      CurrentSurveyRewardTracking: {
        Id: 14,
        SurveyId: 14,
        RewardPrice: 921,
        RewardXp: 81,
        CreatedAt: "2025-06-17T05:19:54.611553Z",
      },
    },
    {
      Id: 15,
      RequesterId: 1,
      Title: "Nghiên cứu nhu cầu mua bảo hiểm cá nhân",
      Description:
        "Khảo sát nhằm mục đích thu thập dữ liệu cho nghiên cứu thị trường.",
      SurveyTypeId: 2,
      SurveyTopicId: 1,
      SurveySpecificTopicId: 2,
      StartDate: "2025-06-01",
      EndDate: null,
      Kpi: 1000,
      SecurityModeId: 2,
      TheoryPrice: 1000000,
      ExtraPrice: 500000,
      TakerBaseRewardPrice: 840,
      ProfitPrice: 300000,
      AllocBaseAmount: 840000,
      AllocTimeAmount: 240000,
      AllocLevelAmount: 120000,
      MaxXp: 100,
      IsAvailable: true,
      SlotsLeft: 100,
      ConfigJsonString: "",
      PublishedAt: null,
      DeletedAt: null,
      CreatedAt: null,
      UpdatedAt: null,
      SurveyStatusId: 2,
      MainImageUrl:
        "https://i.pinimg.com/736x/c7/ef/28/c7ef28b8163e1fac044643d4cd9b609c.jpg",
      BackgroundImageUrl:
        "https://i.pinimg.com/736x/31/85/96/31859600f68c77370c3429cc6baf91e6.jpg",
      CurrentSurveyRewardTracking: {
        Id: 15,
        SurveyId: 15,
        RewardPrice: 1062,
        RewardXp: 94,
        CreatedAt: "2025-06-17T05:19:54.611559Z",
      },
    },
  ],
};

export const SurveyStatuses: SurveyStatus[] = [
  {
    id: 1,
    name: "Editing",
  },
  {
    id: 2,
    name: "Published",
  },
  {
    id: 3,
    name: "Completed",
  },
  {
    id: 4,
    name: "Deleted",
  },
  {
    id: 5,
    name: "Deactivated",
  },
];

export const SurveyTopics: SurveyTopic[] = [
  { id: 1, name: "Ẩm Thực" },
  { id: 2, name: "Giáo Dục" },
  { id: 3, name: "Sức Khỏe & Thể Dục" },
  { id: 4, name: "Công Nghệ" },
  { id: 5, name: "Tài Chính Cá Nhân" },
  { id: 6, name: "Mua sắm & Thương Mại" },
  { id: 7, name: "Du Lịch & Giải Trí" },
  { id: 8, name: "Xã Hội & Hành Vi" },
  { id: 9, name: "Môi Trường" },
  { id: 10, name: "Chính Trị & Pháp Luật" },
];

export const SurveyMeData: SurveyCommunityMe[] = [
  {
    Id: 7,
    Title: "Khảo Sát Test 7",
    Description: "Des cho khảo sát test 7",
    SurveyTopicId: 0,
    SurveySpecificTopicId: 0,
    StartDate: "2025-06-24",
    EndDate: "2025-06-24",
    SecurityModeId: 0,
    IsAvailable: true,
    PublishedAt: "2025-06-24T06:11:23.388Z",
    TakerBaseRewardPrice: 0,
    ConfigJsonString: "string",
    SurveyPrivateData: null,
    SurveyStatusId: 1,
    MainImageUrl:
      "https://i.pinimg.com/736x/6d/89/d1/6d89d12380ce4256077e665596ab1ec5.jpg",
    BackgroundImageUrl: "string",
    QuestionCount: 10,
    CurrentSurveyRewardTracking: {
      Id: 0,
      SurveyId: 0,
      RewardPrice: 0,
      RewardXp: 0,
      CreatedAt: "2025-06-24T06:11:23.388Z",
    },
    SlotsLeft: null,
    SurveyTakenResult: [],
  },
];

export const SurveyTakingData: SurveyTaking = {
  Id: 12345,
  RequesterId: 1,
  Title: "Khảo sát về xu hướng mua sắm Online",
  Description:
    "Đây là Khảo sát nhằm mục đích tìm hiểu xu hướng mua sắm online của người dùng, sau khi nền kinh tế đã phục hồi hậu COVID-19.",
  MarketSurveyVersionStatusId: null,
  SurveyTypeId: 2,
  SurveyTopicId: 1,
  SurveySpecificTopicId: 1,
  SurveyStatusId: 2,
  MainImageUrl:
    "https://i.pinimg.com/736x/a7/4f/4f/a74f4fbb222bbb7365c9d0c5a86f701e.jpg",
  Version: null,
  SecurityModeId: 2,
  BackgroundImageUrl:
    "https://i.pinimg.com/736x/5b/cc/0f/5bcc0fabcfb1899f91d8da939c66e4cb.jpg",
  ConfigJson: {
    BackgroundGradient1Color: null,
    BackgroundGradient2Color: null,
    TitleColor: "#ffffff",
    ContentColor: "#ffffff",
    ButtonBackgroundColor: null,
    ButtonContentColor: null,
    Password: null,
    Brightness: 100, //(OPTIONAL)
  },
  Questions: [
    {
      Id: 1,
      QuestionTypeId: 1,
      Version: null,
      MainImageUrl: null,
      Content: "Bạn có hay mua sắm online không ?",
      Description: null,
      TimeLimit: 3,
      IsVoice: false,
      Order: 1,
      ConfigJson: {},
      Options: [
        {
          SurveyOptionId: 1,
          Content: "Có",
          Order: 1,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 2,
          Content: "Thỉnh thoảng",
          Order: 2,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 3,
          Content: "Không",
          Order: 3,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 2,
      QuestionTypeId: 1,
      Version: null,
      MainImageUrl: null,
      Content: "Tần suất mua sắm online của bạn trong vòng 1 tháng?",
      Description: null,
      TimeLimit: 3,
      IsVoice: false,
      Order: 2,
      ConfigJson: {},
      Options: [
        {
          SurveyOptionId: 4,
          Content: "1 - 3 lần/tháng",
          Order: 1,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 5,
          Content: "4 - 6 lần/tháng",
          Order: 2,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 6,
          Content: "7 - 13 lần/tháng",
          Order: 3,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 7,
          Content: "14 - 21 lần/tháng",
          Order: 4,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 8,
          Content: "Gần như mỗi ngày.",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 3,
      QuestionTypeId: 1,
      Version: null,
      MainImageUrl: null,
      Content: "Sàn thương mại điện tử bạn hay dùng nhất?",
      Description: null,
      TimeLimit: 3,
      IsVoice: false,
      Order: 3,
      ConfigJson: {},
      Options: [
        {
          SurveyOptionId: 9,
          Content: "Shopee",
          Order: 1,
          MainImageUrl:
            "https://i.pinimg.com/736x/b6/3e/e9/b63ee922f91de19dc1c27feb55a74401.jpg",
        },
        {
          SurveyOptionId: 10,
          Content: "Lazada",
          Order: 2,
          MainImageUrl:
            "https://i.pinimg.com/736x/42/05/32/420532558a0bdb98e41085053f9705cd.jpg",
        },
        {
          SurveyOptionId: 11,
          Content: "Tiki",
          Order: 3,
          MainImageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxXZz2KkwktUnS9FLo-mTm1uVouIGs4ukWqg&s",
        },
        {
          SurveyOptionId: 12,
          Content: "Sendo",
          Order: 4,
          MainImageUrl:
            "https://2handofficial.com/wp-content/uploads/2021/08/ma-giam-gia-sendo.png",
        },
        {
          SurveyOptionId: 13,
          Content: "Tiktok Shop",
          Order: 5,
          MainImageUrl:
            "https://dreamagency.vn/wp-content/uploads/2022/08/Tiktok-Shop-1024x1024.jpg",
        },
      ],
    },
    {
      Id: 4,
      QuestionTypeId: 2,
      Version: null,
      MainImageUrl: null,
      Content: "Bạn hay mua những loại sản phẩm nào Online?",
      Description: null,
      TimeLimit: 3,
      IsVoice: false,
      Order: 4,
      ConfigJson: {},
      Options: [
        {
          SurveyOptionId: 14,
          Content: "Mỹ Phẩm",
          Order: 1,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 15,
          Content: "Đồ Công Nghệ",
          Order: 2,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 16,
          Content: "Thời Trang",
          Order: 3,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 17,
          Content: "Đồ Gia Dụng",
          Order: 4,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 18,
          Content: "Những sản phẩm được Sale",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 5,
      QuestionTypeId: 3,
      Version: null,
      MainImageUrl: null,
      Content:
        "Số tiền trung bình bạn dùng cho mua sắm online trong vòng 1 tháng?",
      Description: "Kéo để chọn số tiền tương ứng (VND)",
      TimeLimit: 3,
      IsVoice: false,
      Order: 5,
      ConfigJson: {
        Min: 50000,
        Max: 5000000,
        Step: 10000,
        Unit: "VND",
      },
      Options: [],
    },
    {
      Id: 6,
      QuestionTypeId: 7,
      Version: null,
      MainImageUrl: null,
      Content:
        "Xếp hạng các ưu tiên của bạn khi chọn Sàn Thương Mại Điện Tử là?",
      Description: "Nhấn lần lượt theo xếp hạng của bạn",
      TimeLimit: 3,
      IsVoice: false,
      Order: 6,
      ConfigJson: {},
      Options: [
        {
          SurveyOptionId: 20,
          Content: "Lượng người sử dụng App",
          Order: 1,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 21,
          Content: "Chế độ freeship nhiều",
          Order: 2,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 22,
          Content: "Nhiều voucher giảm giá",
          Order: 3,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 23,
          Content: "Tương tác phản hồi mua hàng nhiều",
          Order: 4,
          MainImageUrl: null,
        },
        {
          SurveyOptionId: 24,
          Content: "Có nhiều nhãn hàng chính hãng trên Sàn",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
  ],
};

export const SurveyListCustomer: SurveyCommunity[] = [
  {
    Id: 1,
    Title: "Khảo sát xu hướng mua sắm online hậu COVID-19",
    Description:
      "Khảo sát này được thiết kế để tìm hiểu sự thay đổi trong thói quen mua sắm online của người tiêu dùng sau đại dịch COVID-19. Với sự phát triển mạnh mẽ của công nghệ và sự thay đổi trong thói quen sống, chúng tôi muốn khám phá những xu hướng mới trong hành vi mua sắm của người tiêu dùng, cũng như tác động của đại dịch đến quyết định mua hàng trực tuyến.",
    SurveyTopicId: 6,
    SurveySpecificTopicId: 1,
    StartDate: "2025-03-20", // FORMAT: YYYY-MM-DD
    EndDate: "2025-04-20", // FORMAT: YYYY-MM-DD
    SecurityModeId: 1,
    IsAvailable: true,
    PublishedAt: "2025-05-25T08:43:29.347Z", // FORMAT: YYYY-MM-DDTH:M:SZ
    TakerBaseRewardPrice: 2000,
    ConfigJsonString: "",
    SurveyPrivateData: null,
    SurveyStatusId: 2,
    SlotsLeft: 10,
    MainImageUrl:
      "https://i.pinimg.com/736x/a7/4f/4f/a74f4fbb222bbb7365c9d0c5a86f701e.jpg",
    BackgroundImageUrl:
      "https://i.pinimg.com/736x/a7/4f/4f/a74f4fbb222bbb7365c9d0c5a86f701e.jpg",
    QuestionCount: 7,
    CurrentSurveyRewardTracking: {
      Id: 1,
      SurveyId: 1,
      RewardPrice: 10500,
      RewardXp: 50,
      CreatedAt: "2025-06-20T08:43:29.347Z",
    },
  },
  {
    Id: 2,
    Title: "Khảo sát trải nghiệm mua sắm tại các chuỗi siêu thị lớn",
    Description:
      "Khảo sát này được thiết kế để thu thập thông tin về trải nghiệm của khách hàng khi mua sắm tại các chuỗi siêu thị lớn. Mục đích của khảo sát là hiểu rõ hơn về mức độ hài lòng của người tiêu dùng đối với chất lượng dịch vụ, sản phẩm và các yếu tố ảnh hưởng đến quyết định mua sắm tại các siêu thị. Các câu hỏi trong khảo sát sẽ giúp đánh giá sự thuận tiện, giá trị dịch vụ và các yếu tố khác liên quan đến trải nghiệm mua sắm tại các chuỗi siêu thị lớn.",
    SurveyTopicId: 6,
    SurveySpecificTopicId: 1,
    StartDate: "2025-03-20", // FORMAT: YYYY-MM-DD
    EndDate: "2025-04-20", // FORMAT: YYYY-MM-DD
    SecurityModeId: 2,
    IsAvailable: true,
    PublishedAt: "2025-03-20T08:43:29.347Z", // FORMAT: YYYY-MM-DDTH:M:SZ
    TakerBaseRewardPrice: 5000,
    ConfigJsonString: "",
    SurveyPrivateData: null,
    SurveyStatusId: 2,
    MainImageUrl:
      "https://i.pinimg.com/736x/de/e4/92/dee492e1e5d140a33d7b56188ae5fc41.jpg",
    BackgroundImageUrl:
      "https://i.pinimg.com/736x/de/e4/92/dee492e1e5d140a33d7b56188ae5fc41.jpg",
    QuestionCount: 5,
    SlotsLeft: 50,
    CurrentSurveyRewardTracking: {
      Id: 1,
      SurveyId: 3,
      RewardPrice: 7500,
      RewardXp: 100,
      CreatedAt: "2025-06-20T08:43:29.347Z",
    },
  },
  {
    Id: 3,
    Title: "Bạn có đang bị Peer-Pressure?",
    Description:
      "Khảo sát này được thiết kế để khám phá mức độ ảnh hưởng của peer-pressure (áp lực từ bạn bè hoặc nhóm) đối với các quyết định và hành vi của bạn. Chúng tôi muốn hiểu rõ hơn về cách mà các yếu tố bên ngoài như bạn bè, gia đình hoặc nhóm xã hội có thể tác động đến các lựa chọn và cảm xúc cá nhân.",
    SurveyTopicId: 8,
    SurveySpecificTopicId: 1,
    StartDate: "2025-03-20", // FORMAT: YYYY-MM-DD
    EndDate: "2025-04-20", // FORMAT: YYYY-MM-DD
    SecurityModeId: 3,
    IsAvailable: true,
    PublishedAt: "2025-01-16T08:43:29.347Z", // FORMAT: YYYY-MM-DDTH:M:SZ
    TakerBaseRewardPrice: 20000,
    ConfigJsonString: "",
    SurveyStatusId: 2,
    SlotsLeft: 100,
    MainImageUrl:
      "https://i.pinimg.com/736x/ef/73/66/ef7366b511372eb95562364dc0fb6697.jpg",
    BackgroundImageUrl:
      "https://i.pinimg.com/736x/ef/73/66/ef7366b511372eb95562364dc0fb6697.jpg",
    QuestionCount: 10,
    CurrentSurveyRewardTracking: {
      Id: 1,
      SurveyId: 3,
      RewardPrice: 50000,
      RewardXp: 250,
      CreatedAt: "2025-06-20T08:43:29.347Z",
    },
    SurveyPrivateData: null,
  },
];

export const SurveyDataMarketCustomer: SurveyDataMarket[] = [
  {
    Id: 1,
    Title: "Bộ Data về Sức Khỏe",
    Description:
      "Bộ dữ liệu này chứa thông tin tổng hợp về sức khỏe cá nhân, bao gồm các chỉ số sinh học, thói quen sinh hoạt, tiền sử bệnh lý và kết quả xét nghiệm định kỳ. Dữ liệu được thu thập từ một nhóm người tham gia trong độ tuổi từ 18 đến 75, nhằm phục vụ cho việc nghiên cứu mối liên hệ giữa các yếu tố lối sống và tình trạng sức khỏe.",
    SurveyTopicId: 3,
    SurveySpecificTopicId: 7,
    StartDate: "2023-05-12",
    EndDate: null,
    SecurityModeId: 2,
    IsAvailable: true,
    PublishedAt: "2023-05-13T07:30:21.312Z",
    TakerBaseRewardPrice: null,
    ConfigJsonString: "",
    SurveyPrivateData: null,
    SurveyStatusId: 2,
    MainImageUrl:
      "https://i.pinimg.com/736x/41/0d/87/410d87a0bb1e10c08c33602061642cc4.jpg",
    BackgroundImageUrl: null,
    QuestionCount: 8,
    SlotsLeft: null,
    VersionTrackings: [
      {
        Version: 1,
        SurveyVersionStatusId: 5,
        ContributorCount: 2000,
        CurrentVersionPrice: 10000000,
        ExpiredAt: "2024-06-21T07:25:06.952Z",
        PublishAt: "2023-05-12T07:25:06.952Z",
      },
      {
        Version: 2,
        SurveyVersionStatusId: 5,
        ContributorCount: 3600,
        CurrentVersionPrice: 10065000,
        ExpiredAt: "2024-12-21T07:25:06.952Z",
        PublishAt: "2024-06-22T07:25:06.952Z",
      },
      {
        Version: 3,
        SurveyVersionStatusId: 2,
        ContributorCount: 500,
        CurrentVersionPrice: 750000,
        ExpiredAt: "2025-06-21T07:25:06.952Z",
        PublishAt: "2024-12-22T07:25:06.952Z",
      },
    ],
  },
  {
    Id: 2,
    Title: "Bộ Data về Tâm Lý Xã Hội",
    Description:
      "Bộ dữ liệu này bao gồm thông tin về các yếu tố tâm lý xã hội ảnh hưởng đến sức khỏe tinh thần và hành vi cá nhân trong cộng đồng. Dữ liệu được thu thập từ các bảng khảo sát định lượng, phỏng vấn và trắc nghiệm tâm lý, với mục tiêu nghiên cứu mối liên hệ giữa môi trường xã hội, cảm xúc, hành vi và sức khỏe tinh thần.",
    SurveyTopicId: 3,
    SurveySpecificTopicId: 8,
    StartDate: "2023-05-12",
    EndDate: null,
    SecurityModeId: 2,
    IsAvailable: true,
    PublishedAt: "2023-05-13T07:30:21.312Z",
    TakerBaseRewardPrice: null,
    ConfigJsonString: "",
    SurveyPrivateData: null,
    SurveyStatusId: 2,
    MainImageUrl:
      "https://i.pinimg.com/736x/4f/ab/d5/4fabd5f8b3ae4c87193d4728fbb3f294.jpg",
    BackgroundImageUrl: null,
    QuestionCount: 8,
    SlotsLeft: null,
    VersionTrackings: [
      {
        Version: 1,
        SurveyVersionStatusId: 5,
        ContributorCount: 2000,
        CurrentVersionPrice: 10000000,
        ExpiredAt: "2024-06-21T07:25:06.952Z",
        PublishAt: "2023-05-12T07:25:06.952Z",
      },
      {
        Version: 2,
        SurveyVersionStatusId: 5,
        ContributorCount: 2100,
        CurrentVersionPrice: 10065000,
        ExpiredAt: "2024-06-21T07:25:06.952Z",
        PublishAt: "2023-05-12T07:25:06.952Z",
      },
      {
        Version: 3,
        SurveyVersionStatusId: 2,
        ContributorCount: 500,
        CurrentVersionPrice: 750000,
        ExpiredAt: "2024-06-21T07:25:06.952Z",
        PublishAt: "2023-05-12T07:25:06.952Z",
      },
    ],
  },
];

export const SurveyDataMarketCustomerDetails: SurveyDataMarketDetails = {
  Id: 0,
  Title: "Bộ Data về Sức Khỏe",
  Description:
    "Bộ dữ liệu này chứa thông tin tổng hợp về sức khỏe cá nhân, bao gồm các chỉ số sinh học, thói quen sinh hoạt, tiền sử bệnh lý và kết quả xét nghiệm định kỳ. Dữ liệu được thu thập từ một nhóm người tham gia trong độ tuổi từ 18 đến 75, nhằm phục vụ cho việc nghiên cứu mối liên hệ giữa các yếu tố lối sống và tình trạng sức khỏe.",
  SurveyTopicId: 3,
  SurveySpecificTopicId: 7,
  StartDate: "2025-06-22",
  EndDate: null,
  SecurityModeId: 2,
  IsAvailable: true,
  PublishedAt: "2025-06-22T09:32:17.169Z",
  TakerBaseRewardPrice: null,
  ConfigJsonString: "",
  SurveyPrivateData: null,
  SurveyStatusId: 2,
  MainImageUrl:
    "https://i.pinimg.com/736x/41/0d/87/410d87a0bb1e10c08c33602061642cc4.jpg",
  BackgroundImageUrl:
    "https://i.pinimg.com/736x/41/0d/87/410d87a0bb1e10c08c33602061642cc4.jpg",
  QuestionCount: null,
  VersionTrackings: [
    {
      Version: 1,
      SurveyVersionStatusId: 5,
      ContributorCount: 2000,
      CurrentVersionPrice: 10000000,
      ExpiredAt: "2024-06-21T07:25:06.952Z",
      PublishAt: "2023-05-12T07:25:06.952Z",
    },
    {
      Version: 2,
      SurveyVersionStatusId: 5,
      ContributorCount: 3600,
      CurrentVersionPrice: 10065000,
      ExpiredAt: "2024-12-21T07:25:06.952Z",
      PublishAt: "2024-06-22T07:25:06.952Z",
    },
    {
      Version: 3,
      SurveyVersionStatusId: 2,
      ContributorCount: 500,
      CurrentVersionPrice: 750000,
      ExpiredAt: "2025-06-21T07:25:06.952Z",
      PublishAt: "2024-12-22T07:25:06.952Z",
    },
  ],
  Questions: [
    {
      Id: 1,
      SurveyId: 1,
      QuestionTypeId: 1,
      Content: "Bạn thường dành bao nhiêu ngày trong tuần để tập thể dục?",
      Description: null,
      TimeLimit: 0,
      IsVoiced: false,
      Order: 1,
      ConfigJsonString: "",
      DeletedAt: null,
      Version: 1,
      MainImageUrl: null,
      Options: [
        {
          Id: 1,
          SurveyQuestionId: 1,
          Content: "1 - 3 lần/ tuần",
          Order: 1,
          MainImageUrl: null,
        },
        {
          Id: 2,
          SurveyQuestionId: 1,
          Content: "4 - 5 lần/ tuần",
          Order: 2,
          MainImageUrl: null,
        },
        {
          Id: 3,
          SurveyQuestionId: 1,
          Content: "Trừ cuối tuần",
          Order: 3,
          MainImageUrl: null,
        },
        {
          Id: 4,
          SurveyQuestionId: 1,
          Content: "Mỗi ngày",
          Order: 4,
          MainImageUrl: null,
        },
        {
          Id: 5,
          SurveyQuestionId: 1,
          Content: "Tôi không tập thể dục",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 2,
      SurveyId: 1,
      QuestionTypeId: 2,
      Content: "Bạn hay tập các môn nào dưới đây?",
      Description: null,
      TimeLimit: 0,
      IsVoiced: false,
      Order: 2,
      ConfigJsonString: "",
      DeletedAt: null,
      Version: 1,
      MainImageUrl: null,
      Options: [
        {
          Id: 1,
          SurveyQuestionId: 2,
          Content: "Gym",
          Order: 1,
          MainImageUrl: null,
        },
        {
          Id: 2,
          SurveyQuestionId: 2,
          Content: "Calisthenics",
          Order: 2,
          MainImageUrl: null,
        },
        {
          Id: 3,
          SurveyQuestionId: 2,
          Content: "Chạy bộ",
          Order: 3,
          MainImageUrl: null,
        },
        {
          Id: 4,
          SurveyQuestionId: 2,
          Content: "Đạp xe",
          Order: 4,
          MainImageUrl: null,
        },
        {
          Id: 5,
          SurveyQuestionId: 2,
          Content: "Thể thao đối kháng (Muay Thái, Boxing, ...)",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 3,
      SurveyId: 1,
      QuestionTypeId: 1,
      Content: "Các thương hiệu đồ thể thao bạn hay sử dụng khi tập luyện?",
      Description: null,
      TimeLimit: 0,
      IsVoiced: false,
      Order: 3,
      ConfigJsonString: "",
      DeletedAt: null,
      Version: 1,
      MainImageUrl: null,
      Options: [
        {
          Id: 1,
          SurveyQuestionId: 3,
          Content: "Coolmate",
          Order: 1,
          MainImageUrl:
            "https://startupwheel.vn/wp-content/uploads/2021/02/Thumbnail-Youtube-Startup-wheel-6.jpg",
        },
        {
          Id: 2,
          SurveyQuestionId: 3,
          Content: "Adidas",
          Order: 2,
          MainImageUrl:
            "https://i.pinimg.com/736x/e7/e5/74/e7e574c4304d140c6b56b6fa5039c838.jpg",
        },
        {
          Id: 3,
          SurveyQuestionId: 3,
          Content: "Nike",
          Order: 3,
          MainImageUrl:
            "https://i.pinimg.com/736x/d7/c7/e5/d7c7e5f8e9f816947ead3165433160d5.jpg",
        },
        {
          Id: 4,
          SurveyQuestionId: 3,
          Content: "Under Armour",
          Order: 4,
          MainImageUrl:
            "https://i.pinimg.com/736x/38/2d/66/382d66614145ec6ab289be10fd0686aa.jpg",
        },
        {
          Id: 5,
          SurveyQuestionId: 2,
          Content: "Lining",
          Order: 5,
          MainImageUrl:
            "https://i.pinimg.com/736x/a3/50/4b/a3504b3b088ea00bccf59a7cf5c3e8f5.jpg",
        },
      ],
    },

    {
      Id: 4,
      SurveyId: 1,
      QuestionTypeId: 1,
      Content: "Bạn thường dành bao nhiêu ngày trong tuần để tập thể dục?",
      Description: null,
      TimeLimit: 0,
      IsVoiced: false,
      Order: 1,
      ConfigJsonString: "",
      DeletedAt: null,
      Version: 2,
      MainImageUrl: null,
      Options: [
        {
          Id: 1,
          SurveyQuestionId: 4,
          Content: "1 - 3 lần/ tuần",
          Order: 1,
          MainImageUrl: null,
        },
        {
          Id: 2,
          SurveyQuestionId: 4,
          Content: "4 - 5 lần/ tuần",
          Order: 2,
          MainImageUrl: null,
        },
        {
          Id: 3,
          SurveyQuestionId: 4,
          Content: "Trừ cuối tuần",
          Order: 3,
          MainImageUrl: null,
        },
        {
          Id: 4,
          SurveyQuestionId: 4,
          Content: "Mỗi ngày",
          Order: 4,
          MainImageUrl: null,
        },
        {
          Id: 5,
          SurveyQuestionId: 4,
          Content: "Tôi không tập thể dục",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 5,
      SurveyId: 1,
      QuestionTypeId: 2,
      Content: "Bạn hay tập các môn nào dưới đây?",
      Description: null,
      TimeLimit: 0,
      IsVoiced: false,
      Order: 2,
      ConfigJsonString: "",
      DeletedAt: null,
      Version: 2,
      MainImageUrl: null,
      Options: [
        {
          Id: 1,
          SurveyQuestionId: 5,
          Content: "Gym",
          Order: 1,
          MainImageUrl: null,
        },
        {
          Id: 2,
          SurveyQuestionId: 5,
          Content: "Calisthenics",
          Order: 2,
          MainImageUrl: null,
        },
        {
          Id: 3,
          SurveyQuestionId: 5,
          Content: "Chạy bộ",
          Order: 3,
          MainImageUrl: null,
        },
        {
          Id: 4,
          SurveyQuestionId: 5,
          Content: "Đạp xe",
          Order: 4,
          MainImageUrl: null,
        },
        {
          Id: 5,
          SurveyQuestionId: 5,
          Content: "Thể thao đối kháng (Muay Thái, Boxing, ...)",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 6,
      SurveyId: 1,
      QuestionTypeId: 3,
      Content: "Bạn thường chi bao nhiều cho đồ dùng tập luyện của bản thân?",
      Description: "Kéo nút để chọn khoảng tiền mong muốn",
      TimeLimit: 0,
      IsVoiced: false,
      Order: 3,
      ConfigJsonString: `{ Min: 50000, Max: 5000000, Step: 10000,Unit: "VND"}`,
      DeletedAt: null,
      Version: 2,
      MainImageUrl: null,
      Options: null,
    },

    {
      Id: 7,
      SurveyId: 1,
      QuestionTypeId: 1,
      Content: "Bạn thường dành bao nhiêu ngày trong tuần để tập thể dục?",
      Description: null,
      TimeLimit: 0,
      IsVoiced: false,
      Order: 1,
      ConfigJsonString: "",
      DeletedAt: null,
      Version: 3,
      MainImageUrl: null,
      Options: [
        {
          Id: 1,
          SurveyQuestionId: 7,
          Content: "1 - 3 lần/ tuần",
          Order: 1,
          MainImageUrl: null,
        },
        {
          Id: 2,
          SurveyQuestionId: 7,
          Content: "4 - 5 lần/ tuần",
          Order: 2,
          MainImageUrl: null,
        },
        {
          Id: 3,
          SurveyQuestionId: 7,
          Content: "Trừ cuối tuần",
          Order: 3,
          MainImageUrl: null,
        },
        {
          Id: 4,
          SurveyQuestionId: 7,
          Content: "Mỗi ngày",
          Order: 4,
          MainImageUrl: null,
        },
        {
          Id: 5,
          SurveyQuestionId: 7,
          Content: "Tôi không tập thể dục",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 8,
      SurveyId: 1,
      QuestionTypeId: 7,
      Content:
        "Xếp hạng các môn thể thao dưới đây dựa trên sự yêu thích của bạn?",
      Description: "Nhấn lần lượt vào các options để xếp hạng",
      TimeLimit: 0,
      IsVoiced: false,
      Order: 2,
      ConfigJsonString: "",
      DeletedAt: null,
      Version: 3,
      MainImageUrl: null,
      Options: [
        {
          Id: 1,
          SurveyQuestionId: 8,
          Content: "Gym",
          Order: 1,
          MainImageUrl: null,
        },
        {
          Id: 2,
          SurveyQuestionId: 8,
          Content: "Calisthenics",
          Order: 2,
          MainImageUrl: null,
        },
        {
          Id: 3,
          SurveyQuestionId: 8,
          Content: "Chạy bộ",
          Order: 3,
          MainImageUrl: null,
        },
        {
          Id: 4,
          SurveyQuestionId: 5,
          Content: "Đạp xe",
          Order: 4,
          MainImageUrl: null,
        },
        {
          Id: 5,
          SurveyQuestionId: 5,
          Content: "Thể thao đối kháng (Muay Thái, Boxing, ...)",
          Order: 5,
          MainImageUrl: null,
        },
      ],
    },
    {
      Id: 9,
      SurveyId: 1,
      QuestionTypeId: 3,
      Content: "Bạn thường chi bao nhiều cho đồ dùng tập luyện của bản thân?",
      Description: null,
      TimeLimit: 0,
      IsVoiced: false,
      Order: 3,
      ConfigJsonString: `{ Min: 50000, Max: 5000000, Step: 10000,Unit: "VND"}`,
      DeletedAt: null,
      Version: 3,
      MainImageUrl: null,
      Options: null,
    },
  ],
};
